---
- name: Configure intervlan routing and deploy OSPF
  hosts: dist
  connection: local
  gather_facts: no
  tasks:
    - name: Create interfaces vlan
      with_items: "{{vlans}}"
      ios_vlan:
        vlan_id: "{{item.id}}"
        name: "{{item.desc}}"
        state: present
    
    - name: Generate config file cfg for distribution switchs
      template: src=files/deploy_inter_vlan_dist.j2 dest={{inventory_hostname}}.cfg
    - name: Deploy inter_vlan routing
      ios_config:
        src: "{{inventory_hostname}}.cfg"
      